# ==========================================
# MySQL Configuration
# ==========================================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/sa?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:pa}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ==========================================
# JPA / Hibernate Configuration
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
# ==========================================
# Monitoring & Health Checks (Actuator)
# ==========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# ==========================================
# Kubernetes & Application Logic Tracking
# ==========================================
# Captures the HOSTNAME environment variable injected by K8s.
app.pod.name=${HOSTNAME:local-dev}
# Feature Toggles:
feature.old-consumer.enabled=false

app.batch.size=${BATCH_SIZE:10}

gemini.api.key=AIzaSyCWcONuQXRSjb372xNCwCiX9h4hBpb26Wk